- src: https://github.com/zbitmanis/role_prepare_kubernetes_node.git 
  version: v1.2
  name: prepare_kubernetes_node

- src: https://github.com/zbitmanis/role_install_kubernetes_node.git
  version: v1.1
  name: install_kubernetes_node

- src: https://github.com:zbitmanis/role_argocd_install.git
  version: v1.0
  name: argocd_install
